baseURL = "https://fiverr-growhaus.netlify.app"
languageCode = "id-ID"
defaultContentLanguage = "id"
title = "Growhaus"
summaryLength = 10
RelativeURLs = false
CanonifyURLs = true
enableRobotsTXT = true
enableEmoji = true
paginate = 8
enableGitInfo = true
pygmentsCodefences = true 
pygmentsUseClasses = true

[params]
  author = "John Doe"
  site_name = "Growhaus"
  description = "Growhaus description"
  locale = "en-US"
  type = "website"

  primary_color = "#009A16" # Green Color

  landing_title = "Online Music Collaboration Platform"
  landing_description = "Lorem ispum dolor si amet jue viole grace"
  background_image = "/assets/images/bg.webp"

  learn_more_url = "#"
  try_now_url = "#"

  about = "Growhaus Lorem ipsum dolor sit amet, consectetur adipiscing elit. Enim, lectus lorem scelerisque enim. Tellus ante placerat metus non, mattis gravida odio sed. Pellentesque lobortis dui neque nec potenti. Pretium amet sed posuere curabitur adipiscing dignissim. Lacinia odio congue nulla et vitae in quis eget non. Augue lacus at arcu vulputate eget tincidunt mi, potenti odio. Duis rhoncus urna neque dui in cursus eu gravida adipiscing."

### Get Started
[[params.slides]]
  slideType = "view"
  view = "slide-views/get-started.html"

### Slide 1
[[params.slides]]
  slideType = "input"
  id = "email"
  title = "Your Email Address"
  name = "emailAddress"
  type = "email"
  placeholder = "example@gmail.com"

### Slide 2
[[params.slides]]
  slideType = "input"
  id = "name"
  title = "Your Name"
  name = "entry.177899891"
  type = "text"
  placeholder = "Your name"

### Slide 3
[[params.slides]]
  slideType = "input"
  id = "store-url"
  title = "Store URL"
  name = "entry.87908930"
  type = "url"
  placeholder = "https://mysite.com"

### Slide 4
[[params.slides]]
  slideType = "view"
  view = "slide-views/login-shopify.html"

### Slide 5
[[params.slides]]
  slideType = "input"
  id = "total-revenue"
  title = "Total Revenue"
  name = "entry.1591179306"
  type = "text"
  placeholder = "Your Answer"

### Slide 6
[[params.slides]]
  slideType = "input"
  id = "total-adspend"
  title = "Total Adspend"
  name = "entry.1006791840"
  type = "text"
  placeholder = "Your Answer"

### Slide 7
[[params.slides]]
  slideType = "input"
  id = "sessions"
  title = "Sessions"
  name = "entry.1168260182"
  type = "text"
  placeholder = "Your Answer"

### Slide 8
[[params.slides]]
  slideType = "input"
  id = "add-to-chart"
  title = "Add to Chart"
  name = "entry.745973099"
  type = "text"
  placeholder = "Your Answer"

### Slide 9
[[params.slides]]
  slideType = "input"
  id = "reached-checkout"
  title = "Reached Checkout"
  name = "entry.1531030102"
  type = "text"
  placeholder = "Your answer"

### Slide 10
[[params.slides]]
  slideType = "input"
  id = "sessions-converted"
  title = "Sessions Converted"
  name = "entry.843800738"
  type = "text"
  placeholder = "Your answer"

### Slide 11
[[params.slides]]
  slideType = "input"
  id = "returning-customer-rate"
  title = "Returning Customer Rate"
  name = "entry.173864781"
  type = "text"
  placeholder = "Your answer"

### Slide 12
[[params.slides]]
  slideType = "view"
  view = "slide-views/login-klaviyo.html"

### Slide 13
[[params.slides]]
  slideType = "input"
  id = "revenue-form-klaviyo"
  title = "Revenue from Klaviyo"
  name = "entry.1498452875"
  type = "number"
  placeholder = "Your answer"

### Slide 14
[[params.slides]]
  slideType = "input"
  id = "revenue-from-flows"
  title = "Revenue from Flows"
  name = "entry.754883273"
  type = "number"
  placeholder = "Your answer"

### Slide 15
[[params.slides]]
  slideType = "input"
  id = "revenue-from-campaigns"
  title = "Revenue from Campaigns"
  name = "entry.867833551"
  type = "number"
  placeholder = "Your answer"

### Slide 16
[[params.slides]]
  slideType = "input"
  id = "email-revenue"
  title = "Email Revenue"
  name = "entry.1764438909"
  type = "number"
  placeholder = "Your answer"

### Slide 17
[[params.slides]]
  slideType = "input"
  id = "sms-revenue"
  title = "SMS Revenue"
  name = "entry.475474516"
  type = "number"
  placeholder = "Your answer"

### Slide 18
[[params.slides]]
  slideType = "view"
  view = "slide-views/signup-klaviyo.html"

### Slide 19
[[params.slides]]
  slideType = "input-radio"
  id = "your-rating"
  title = "Please Your Rating"
  name = "entry.272409792"
  type = "radio"
  values = ['This is very helpful', 'Very Good', 'Good', 'Not helpful']

### Slide 20
[[params.slides]]
  slideType = "view"
  view = "slide-views/submit-view.html"
